// --------------------------------------------------------
// DAX Measures for Summary Page
// --------------------------------------------------------

Total Customers = COUNT('bd_churn customer_data'[Customer_ID])

New Joiners = CALCULATE(COUNT('bd_churn customer_data'[Customer_ID]), 'bd_churn customer_data'[Customer_Status] = "Joined")

Total Churn = SUM('bd_churn customer_data'[Churn Status])

Churn Rate = [Total Churn] / [Total Customers]


// --------------------------------------------------------
// DAX Measures for Churn Prediction Page
// --------------------------------------------------------

Count Predicted Churner = COUNT(Predictions[Customer_ID]) + 0

Title Predicted Churners = "COUNT OF PREDICTED CHURNERS : " & COUNT(Predictions[Customer_ID])
